import { useState, useEffect, useCallback } from 'react';
import { X, Download, Printer, FileText, FileSpreadsheet, Loader2, AlertCircle, ExternalLink, Maximize2, Minimize2 } from 'lucide-react';
import { getSignedAttachmentUrl } from '../services/auth';
import { isSupabaseConfigured } from '../lib/supabase';
import type { Transaction } from '../hooks/useTransactions';
import { useAuthStore } from '../store/auth';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  transaction: Transaction | null;
}

export default function DocumentViewerModal({ isOpen, onClose, transaction }: Props) {
  const company = useAuthStore(s => s.company);
  const [activeTab, setActiveTab] = useState<'file' | 'summary'>('file');
  const [signedUrl, setSignedUrl] = useState<string | null>(null);
  const [loadingUrl, setLoadingUrl] = useState(false);
  const [urlError, setUrlError] = useState<string | null>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [pdfZoom, setPdfZoom] = useState<string>('FitH');

  // Track browser fullscreen state
  useEffect(() => {
    const onFSChange = () => setIsFullscreen(!!document.fullscreenElement);
    document.addEventListener('fullscreenchange', onFSChange);
    return () => document.removeEventListener('fullscreenchange', onFSChange);
  }, []);

  // Escape closes the viewer (but not if the browser fullscreen overlay is active)
  const handleClose = useCallback(() => {
    if (document.fullscreenElement) document.exitFullscreen();
    else onClose();
  }, [onClose]);

  useEffect(() => {
    if (!isOpen) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') handleClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [isOpen, handleClose]);

  const toggleFullscreen = () => {
    if (document.fullscreenElement) document.exitFullscreen();
    else document.documentElement.requestFullscreen?.();
  };

  useEffect(() => {
    setSignedUrl(null);
    setUrlError(null);
    if (!isOpen || !transaction?.attachment_url) {
      setActiveTab('summary');
      return;
    }
    setActiveTab('file');
    if (!isSupabaseConfigured) {
      setUrlError('File preview not available in demo mode.');
      return;
    }
    setLoadingUrl(true);
    getSignedAttachmentUrl(transaction.attachment_url).then(url => {
      setLoadingUrl(false);
      if (url) setSignedUrl(url);
      else setUrlError('Could not load file. The link may have expired — try closing and reopening.');
    });
  }, [isOpen, transaction?.attachment_url]);

  if (!isOpen || !transaction) return null;

  const tx = transaction;
  const companyName = company?.name || 'FinERP';
  const currency = company?.currency || 'QR';
  const hasAttachment = !!tx.attachment_url;
  const ext = (tx.attachment_url?.split('.').pop() ?? '').toLowerCase();
  const isPdf   = ext === 'pdf';
  const isImage = ['jpg', 'jpeg', 'png', 'webp'].includes(ext);

  const handlePrint = () => window.print();

  const handleDownloadGeneratedPDF = async () => {
    try {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text(companyName.toUpperCase(), 14, 25);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(130);
      doc.text(new Date().toLocaleDateString(), 14, 32);

      doc.setFontSize(16);
      doc.setTextColor(150);
      doc.text(tx.type.toUpperCase(), 196, 25, { align: 'right' });

      doc.setFontSize(9);
      doc.setTextColor(80);
      doc.text(`Status: ${tx.status.toUpperCase()}`, 196, 32, { align: 'right' });

      let y = 50;
      doc.setDrawColor(220);
      doc.line(14, y, 196, y);
      y += 10;

      const addField = (label: string, value: string) => {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(120);
        doc.setFontSize(8);
        doc.text(label, 14, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(40);
        doc.setFontSize(10);
        doc.text(value, 14, y + 5);
        y += 14;
      };

      if (tx.invoice_number) addField('Invoice Number', tx.invoice_number);
      if (tx.client_name)    addField('Client',         tx.client_name);
      addField('Project',     tx.project);
      addField('Description', tx.desc);
      addField('Date',        tx.date);
      if (tx.due_date) addField('Due Date', tx.due_date);

      y += 5;
      doc.setDrawColor(220);
      doc.line(14, y, 196, y);
      y += 12;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40);
      doc.text('TOTAL', 14, y);
      doc.setTextColor(37, 99, 235);
      doc.text(`${currency} ${Math.abs(tx.amount).toLocaleString()}`, 196, y, { align: 'right' });

      doc.setFontSize(8);
      doc.setTextColor(180);
      doc.text('Generated by FinERP Financial Systems', 105, 280, { align: 'center' });

      doc.save(`${tx.invoice_number || tx.type}-${tx.id}.pdf`);
    } catch (err) {
      console.error('PDF generation failed:', err);
    }
  };

  const handleDownloadExcel = async () => {
    try {
      const ExcelJS = await import('exceljs');
      const wb = new ExcelJS.Workbook();
      const ws = wb.addWorksheet('Transaction');
      ws.columns = [
        { header: 'Date',        key: 'date',     width: 14 },
        { header: 'Invoice #',   key: 'invoice',  width: 18 },
        { header: 'Type',        key: 'type',     width: 12 },
        { header: 'Description', key: 'desc',     width: 32 },
        { header: 'Project',     key: 'project',  width: 22 },
        { header: 'Client',      key: 'client',   width: 22 },
        { header: 'Amount',      key: 'amount',   width: 14 },
        { header: 'Currency',    key: 'currency', width: 10 },
        { header: 'Status',      key: 'status',   width: 12 },
        { header: 'Due Date',    key: 'dueDate',  width: 14 },
      ];
      ws.addRow({
        date:     tx.date,
        invoice:  tx.invoice_number || '',
        type:     tx.type,
        desc:     tx.desc,
        project:  tx.project,
        client:   tx.client_name || '',
        amount:   Math.abs(tx.amount),
        currency,
        status:   tx.status,
        dueDate:  tx.due_date || '',
      });
      const buffer = await wb.xlsx.writeBuffer();
      const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${tx.invoice_number || tx.type}-${tx.id}.xlsx`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Excel generation failed:', err);
    }
  };

  const statusColor: Record<string, string> = {
    draft:    'bg-slate-100 text-slate-600 border-slate-200',
    pending:  'bg-amber-50 text-amber-700 border-amber-200',
    approved: 'bg-blue-50 text-blue-700 border-blue-200',
    paid:     'bg-emerald-50 text-emerald-700 border-emerald-200',
    rejected: 'bg-red-50 text-red-700 border-red-200',
  };

  // Full-screen viewer — covers sidebar, navbar, everything
  return (
    <div className="fixed inset-0 z-[9999] h-screen flex flex-col overflow-hidden bg-slate-900 animate-fade-in">

      {/* Header — pinned, never scrolls away */}
      <div className="shrink-0 flex items-center justify-between px-4 h-12 bg-slate-800 border-b border-slate-700">
        <div className="flex items-center gap-3 min-w-0">
          <FileText className="w-4 h-4 text-blue-400 shrink-0" />
          <span className="text-sm font-semibold text-white truncate">
            {tx.invoice_number || tx.type} — {tx.desc}
          </span>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          {hasAttachment && (
            <div className="flex bg-slate-700 rounded-lg p-0.5 mr-1">
              <button
                onClick={() => setActiveTab('file')}
                className={`px-3 py-1 text-xs font-bold rounded-md transition-colors ${activeTab === 'file' ? 'bg-slate-500 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'}`}
              >
                Uploaded File
              </button>
              <button
                onClick={() => setActiveTab('summary')}
                className={`px-3 py-1 text-xs font-bold rounded-md transition-colors ${activeTab === 'summary' ? 'bg-slate-500 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'}`}
              >
                Summary
              </button>
            </div>
          )}
          {activeTab === 'file' && signedUrl && (
            <>
              {isPdf && (
                <select
                  value={pdfZoom}
                  onChange={e => setPdfZoom(e.target.value)}
                  className="text-xs font-bold bg-slate-700 text-slate-200 border border-slate-600 rounded-lg px-2 py-1.5 cursor-pointer hover:bg-slate-600 transition-colors"
                  title="Zoom level"
                >
                  <option value="FitH">Fit Width</option>
                  <option value="Fit">Fit Page</option>
                  <option value="100">100%</option>
                  <option value="125">125%</option>
                  <option value="150">150%</option>
                </select>
              )}
              <a
                href={signedUrl}
                target="_blank"
                rel="noreferrer"
                className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold transition-colors"
              >
                <Download className="w-3.5 h-3.5" /> Download
              </a>
            </>
          )}
          {activeTab === 'summary' && (
            <>
              <button onClick={handlePrint} className="p-2 text-slate-400 hover:text-white hover:bg-slate-700 rounded-lg transition-colors hidden sm:flex" title="Print">
                <Printer className="w-4 h-4" />
              </button>
              <button onClick={handleDownloadGeneratedPDF} className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold transition-colors">
                <FileText className="w-3.5 h-3.5" /> PDF
              </button>
              <button onClick={handleDownloadExcel} className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-bold transition-colors">
                <FileSpreadsheet className="w-3.5 h-3.5" /> Excel
              </button>
            </>
          )}
          {/* Fullscreen toggle */}
          <button
            onClick={toggleFullscreen}
            className="p-2 bg-slate-700 hover:bg-slate-600 text-slate-300 hover:text-white rounded-lg transition-colors"
            title={isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
          >
            {isFullscreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
          </button>
          {/* Close — always visible, Esc also works */}
          <button
            onClick={handleClose}
            className="p-2 bg-slate-700 hover:bg-red-600 text-slate-300 hover:text-white rounded-lg transition-colors"
            title="Close (Esc)"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Body — flex-1 fills all height below header; w-full spans the full width */}
      <div className="flex-1 min-h-0 w-full flex flex-col">

        {/* ── Uploaded File Tab ── */}
        {activeTab === 'file' && (
          // relative + flex-1 gives this div the full remaining height.
          // Children use absolute inset-0 so they fill it precisely
          // without depending on flex alignment (items-center would break h-full on iframe).
          <div className="flex-1 min-h-0 w-full relative bg-slate-800">
            {loadingUrl && (
              <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 text-slate-400">
                <Loader2 className="w-8 h-8 animate-spin" />
                <span className="text-sm">Loading file…</span>
              </div>
            )}
            {urlError && (
              <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 text-red-400 px-4 text-center">
                <AlertCircle className="w-8 h-8" />
                <p className="text-sm font-medium max-w-xs">{urlError}</p>
              </div>
            )}
            {signedUrl && !loadingUrl && (
              isPdf ? (
                // absolute inset-0 guarantees the iframe fills every pixel of the container
                <iframe
                  key={pdfZoom}
                  src={
                    pdfZoom === 'FitH' || pdfZoom === 'Fit'
                      ? `${signedUrl}#toolbar=0&view=${pdfZoom}`
                      : `${signedUrl}#toolbar=0&zoom=${pdfZoom}`
                  }
                  title="Attached document"
                  className="absolute inset-0 w-full h-full border-0"
                />
              ) : isImage ? (
                <div className="absolute inset-0 overflow-y-auto flex items-center justify-center p-6">
                  <img
                    src={signedUrl}
                    alt="Attached document"
                    className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
                  />
                </div>
              ) : (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-4 text-slate-400">
                  <FileText className="w-12 h-12 text-blue-400" />
                  <p className="text-sm font-medium">Preview not available for this file type.</p>
                  <a
                    href={signedUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-sm font-bold transition-colors"
                  >
                    <ExternalLink className="w-4 h-4" /> Open File
                  </a>
                </div>
              )
            )}
          </div>
        )}

          {/* ── Summary Tab — scrolls within the body area ── */}
          {activeTab === 'summary' && (
            <div className="flex-1 min-h-0 overflow-y-auto p-8 bg-slate-50 dark:bg-slate-950/50">
              <div className="bg-white dark:bg-gray-900 shadow-xl shadow-slate-200/50 dark:shadow-none border border-slate-100 dark:border-slate-800 p-12 max-w-3xl mx-auto min-h-[500px]">
                <div className="flex justify-between items-start mb-12">
                  <div>
                    <h1 className="text-3xl font-black text-slate-900 dark:text-white mb-2 tracking-tight">
                      {companyName.toUpperCase()}
                    </h1>
                    <p className="text-slate-500 dark:text-slate-400 text-sm">{new Date().toLocaleDateString()}</p>
                  </div>
                  <div className="text-right">
                    <h2 className="text-2xl font-bold text-slate-300 dark:text-slate-700 uppercase tracking-widest mb-3">
                      {tx.type}
                    </h2>
                    <span className={`px-4 py-1.5 rounded border text-sm font-bold tracking-wider ${statusColor[tx.status] || statusColor.draft}`}>
                      {tx.status.toUpperCase()}
                    </span>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 sm:gap-12 mb-8 sm:mb-12">
                  <div className="space-y-4">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest border-b border-slate-100 dark:border-slate-800 pb-2 mb-4">Details</h4>
                    {tx.invoice_number && (
                      <div>
                        <span className="block text-xs text-slate-400">Invoice Number</span>
                        <span className="font-bold text-slate-900 dark:text-white font-mono">{tx.invoice_number}</span>
                      </div>
                    )}
                    {tx.client_name && (
                      <div>
                        <span className="block text-xs text-slate-400">Client</span>
                        <span className="font-bold text-slate-900 dark:text-white">{tx.client_name}</span>
                      </div>
                    )}
                    <div>
                      <span className="block text-xs text-slate-400">Project</span>
                      <span className="font-medium text-slate-700 dark:text-slate-300">{tx.project}</span>
                    </div>
                  </div>
                  <div className="space-y-4 text-right">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest border-b border-slate-100 dark:border-slate-800 pb-2 mb-4">Information</h4>
                    <div>
                      <span className="block text-xs text-slate-400">ID</span>
                      <span className="font-mono text-slate-900 dark:text-white">#{tx.id}</span>
                    </div>
                    <div>
                      <span className="block text-xs text-slate-400">Date</span>
                      <span className="font-medium text-slate-700 dark:text-slate-300">{tx.date}</span>
                    </div>
                    {tx.due_date && (
                      <div>
                        <span className="block text-xs text-slate-400">Due Date</span>
                        <span className="font-medium text-slate-700 dark:text-slate-300">{tx.due_date}</span>
                      </div>
                    )}
                  </div>
                </div>

                <table className="w-full mb-12">
                  <thead>
                    <tr className="border-b-2 border-slate-100 dark:border-slate-800 text-left">
                      <th className="py-4 text-xs font-bold text-slate-400 uppercase tracking-widest pl-4">Description</th>
                      <th className="py-4 text-xs font-bold text-slate-400 uppercase tracking-widest text-right pr-4">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="py-6 pl-4">
                        <div className="font-bold text-slate-900 dark:text-white mb-1">{tx.desc}</div>
                        <div className="text-sm text-slate-500">{tx.project} • {tx.type}</div>
                      </td>
                      <td className="py-6 pr-4 text-right font-bold text-slate-900 dark:text-white">
                        {currency} {Math.abs(tx.amount).toLocaleString()}
                      </td>
                    </tr>
                  </tbody>
                  <tfoot>
                    <tr className="border-t-2 border-slate-900 dark:border-white">
                      <td className="py-6 pl-4 font-black text-xl text-slate-900 dark:text-white uppercase">Total</td>
                      <td className="py-6 pr-4 text-right font-black text-xl text-blue-600 dark:text-blue-400">
                        {currency} {Math.abs(tx.amount).toLocaleString()}
                      </td>
                    </tr>
                  </tfoot>
                </table>

                <div className="text-center pt-12 border-t border-slate-100 dark:border-slate-800">
                  <p className="text-xs text-slate-300 dark:text-slate-600 font-bold uppercase tracking-widest">
                    Generated by FinERP Financial Systems
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>

      <style>{`
        @media print {
          body * { visibility: hidden; }
          .fixed, .fixed * { visibility: visible; }
          .fixed { position: absolute; left: 0; top: 0; width: 100%; height: 100%; background: white; }
        }
      `}</style>
    </div>
  );
}
