import { useState, useEffect } from 'react';
import { X, Download, Printer, FileText, FileSpreadsheet, Loader2, AlertCircle, ExternalLink } from 'lucide-react';
import { getSignedAttachmentUrl } from '../services/auth';
import { isSupabaseConfigured } from '../lib/supabase';
import type { Transaction } from '../hooks/useTransactions';
import { useAuthStore } from '../store/auth';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  transaction: Transaction | null;
}

export default function DocumentViewerModal({ isOpen, onClose, transaction }: Props) {
  const company = useAuthStore(s => s.company);
  const [activeTab, setActiveTab] = useState<'file' | 'summary'>('file');
  const [signedUrl, setSignedUrl] = useState<string | null>(null);
  const [loadingUrl, setLoadingUrl] = useState(false);
  const [urlError, setUrlError] = useState<string | null>(null);

  useEffect(() => {
    setSignedUrl(null);
    setUrlError(null);
    if (!isOpen || !transaction?.attachment_url) {
      setActiveTab('summary');
      return;
    }
    setActiveTab('file');
    if (!isSupabaseConfigured) {
      setUrlError('File preview not available in demo mode.');
      return;
    }
    setLoadingUrl(true);
    getSignedAttachmentUrl(transaction.attachment_url).then(url => {
      setLoadingUrl(false);
      if (url) setSignedUrl(url);
      else setUrlError('Could not load file. The link may have expired — try closing and reopening.');
    });
  }, [isOpen, transaction?.attachment_url]);

  if (!isOpen || !transaction) return null;

  const tx = transaction;
  const companyName = company?.name || 'FinERP';
  const currency = company?.currency || 'QR';
  const hasAttachment = !!tx.attachment_url;
  const ext = (tx.attachment_url?.split('.').pop() ?? '').toLowerCase();
  const isPdf   = ext === 'pdf';
  const isImage = ['jpg', 'jpeg', 'png', 'webp'].includes(ext);

  const handlePrint = () => window.print();

  const handleDownloadGeneratedPDF = async () => {
    try {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text(companyName.toUpperCase(), 14, 25);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(130);
      doc.text(new Date().toLocaleDateString(), 14, 32);

      doc.setFontSize(16);
      doc.setTextColor(150);
      doc.text(tx.type.toUpperCase(), 196, 25, { align: 'right' });

      doc.setFontSize(9);
      doc.setTextColor(80);
      doc.text(`Status: ${tx.status.toUpperCase()}`, 196, 32, { align: 'right' });

      let y = 50;
      doc.setDrawColor(220);
      doc.line(14, y, 196, y);
      y += 10;

      const addField = (label: string, value: string) => {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(120);
        doc.setFontSize(8);
        doc.text(label, 14, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(40);
        doc.setFontSize(10);
        doc.text(value, 14, y + 5);
        y += 14;
      };

      if (tx.invoice_number) addField('Invoice Number', tx.invoice_number);
      if (tx.client_name)    addField('Client',         tx.client_name);
      addField('Project',     tx.project);
      addField('Description', tx.desc);
      addField('Date',        tx.date);
      if (tx.due_date) addField('Due Date', tx.due_date);

      y += 5;
      doc.setDrawColor(220);
      doc.line(14, y, 196, y);
      y += 12;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40);
      doc.text('TOTAL', 14, y);
      doc.setTextColor(37, 99, 235);
      doc.text(`${currency} ${Math.abs(tx.amount).toLocaleString()}`, 196, y, { align: 'right' });

      doc.setFontSize(8);
      doc.setTextColor(180);
      doc.text('Generated by FinERP Financial Systems', 105, 280, { align: 'center' });

      doc.save(`${tx.invoice_number || tx.type}-${tx.id}.pdf`);
    } catch (err) {
      console.error('PDF generation failed:', err);
    }
  };

  const handleDownloadExcel = async () => {
    try {
      const { utils, writeFile } = await import('xlsx');
      const data = [{
        'Date':        tx.date,
        'Invoice #':   tx.invoice_number || '',
        'Type':        tx.type,
        'Description': tx.desc,
        'Project':     tx.project,
        'Client':      tx.client_name || '',
        'Amount':      Math.abs(tx.amount),
        'Currency':    currency,
        'Status':      tx.status,
        'Due Date':    tx.due_date || '',
      }];
      const ws = utils.json_to_sheet(data);
      const wb = utils.book_new();
      utils.book_append_sheet(wb, ws, 'Transaction');
      writeFile(wb, `${tx.invoice_number || tx.type}-${tx.id}.xlsx`);
    } catch (err) {
      console.error('Excel generation failed:', err);
    }
  };

  const statusColor: Record<string, string> = {
    draft:    'bg-slate-100 text-slate-600 border-slate-200',
    pending:  'bg-amber-50 text-amber-700 border-amber-200',
    approved: 'bg-blue-50 text-blue-700 border-blue-200',
    paid:     'bg-emerald-50 text-emerald-700 border-emerald-200',
    rejected: 'bg-red-50 text-red-700 border-red-200',
  };

  // Full-screen viewer — covers sidebar, navbar, everything
  return (
    <div className="fixed inset-0 z-[9999] flex flex-col bg-slate-900 animate-fade-in">

      {/* Header — pinned, never scrolls away */}
      <div className="shrink-0 flex items-center justify-between px-4 h-12 bg-slate-800 border-b border-slate-700">
        <div className="flex items-center gap-3 min-w-0">
          <FileText className="w-4 h-4 text-blue-400 shrink-0" />
          <span className="text-sm font-semibold text-white truncate">
            {tx.invoice_number || tx.type} — {tx.desc}
          </span>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          {hasAttachment && (
            <div className="flex bg-slate-700 rounded-lg p-0.5 mr-1">
              <button
                onClick={() => setActiveTab('file')}
                className={`px-3 py-1 text-xs font-bold rounded-md transition-colors ${activeTab === 'file' ? 'bg-slate-500 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'}`}
              >
                Uploaded File
              </button>
              <button
                onClick={() => setActiveTab('summary')}
                className={`px-3 py-1 text-xs font-bold rounded-md transition-colors ${activeTab === 'summary' ? 'bg-slate-500 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'}`}
              >
                Summary
              </button>
            </div>
          )}
          {activeTab === 'file' && signedUrl && (
            <a
              href={signedUrl}
              target="_blank"
              rel="noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold transition-colors"
            >
              <Download className="w-3.5 h-3.5" /> Download
            </a>
          )}
          {activeTab === 'summary' && (
            <>
              <button onClick={handlePrint} className="p-2 text-slate-400 hover:text-white hover:bg-slate-700 rounded-lg transition-colors hidden sm:flex" title="Print">
                <Printer className="w-4 h-4" />
              </button>
              <button onClick={handleDownloadGeneratedPDF} className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold transition-colors">
                <FileText className="w-3.5 h-3.5" /> PDF
              </button>
              <button onClick={handleDownloadExcel} className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-bold transition-colors">
                <FileSpreadsheet className="w-3.5 h-3.5" /> Excel
              </button>
            </>
          )}
          {/* Close button — always visible, high contrast */}
          <button
            onClick={onClose}
            className="ml-2 p-2 bg-slate-700 hover:bg-red-600 text-slate-300 hover:text-white rounded-lg transition-colors"
            title="Close (Esc)"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Body — fills all remaining height */}
      <div className="flex-1 min-h-0 flex flex-col">

        {/* ── Uploaded File Tab ── */}
        {activeTab === 'file' && (
          <div className="flex-1 min-h-0 flex flex-col items-center justify-center bg-slate-800">
            {loadingUrl && (
              <div className="flex flex-col items-center gap-3 text-slate-400">
                <Loader2 className="w-8 h-8 animate-spin" />
                <span className="text-sm">Loading file…</span>
              </div>
            )}
            {urlError && (
              <div className="flex flex-col items-center gap-3 text-red-400 max-w-xs text-center px-4">
                <AlertCircle className="w-8 h-8" />
                <p className="text-sm font-medium">{urlError}</p>
              </div>
            )}
            {signedUrl && !loadingUrl && (
              isPdf ? (
                // #toolbar=0 hides browser's floating PDF toolbar
                // #view=FitH makes the page fill the full width (removes grey side margins)
                <iframe
                  src={`${signedUrl}#toolbar=0&view=FitH`}
                  title="Attached document"
                  className="w-full h-full border-0"
                />
              ) : isImage ? (
                <div className="w-full h-full overflow-auto flex items-center justify-center p-6">
                  <img
                    src={signedUrl}
                    alt="Attached document"
                    className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
                  />
                </div>
              ) : (
                <div className="flex flex-col items-center gap-4 text-slate-400">
                  <FileText className="w-12 h-12 text-blue-400" />
                  <p className="text-sm font-medium">Preview not available for this file type.</p>
                  <a
                    href={signedUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-sm font-bold transition-colors"
                  >
                    <ExternalLink className="w-4 h-4" /> Open File
                  </a>
                </div>
              )
            )}
          </div>
        )}

          {/* ── Summary Tab — scrolls within the body area ── */}
          {activeTab === 'summary' && (
            <div className="flex-1 min-h-0 overflow-y-auto p-8 bg-slate-50 dark:bg-slate-950/50">
              <div className="bg-white dark:bg-gray-900 shadow-xl shadow-slate-200/50 dark:shadow-none border border-slate-100 dark:border-slate-800 p-12 max-w-3xl mx-auto min-h-[500px]">
                <div className="flex justify-between items-start mb-12">
                  <div>
                    <h1 className="text-3xl font-black text-slate-900 dark:text-white mb-2 tracking-tight">
                      {companyName.toUpperCase()}
                    </h1>
                    <p className="text-slate-500 dark:text-slate-400 text-sm">{new Date().toLocaleDateString()}</p>
                  </div>
                  <div className="text-right">
                    <h2 className="text-2xl font-bold text-slate-300 dark:text-slate-700 uppercase tracking-widest mb-3">
                      {tx.type}
                    </h2>
                    <span className={`px-4 py-1.5 rounded border text-sm font-bold tracking-wider ${statusColor[tx.status] || statusColor.draft}`}>
                      {tx.status.toUpperCase()}
                    </span>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-12 mb-12">
                  <div className="space-y-4">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest border-b border-slate-100 dark:border-slate-800 pb-2 mb-4">Details</h4>
                    {tx.invoice_number && (
                      <div>
                        <span className="block text-xs text-slate-400">Invoice Number</span>
                        <span className="font-bold text-slate-900 dark:text-white font-mono">{tx.invoice_number}</span>
                      </div>
                    )}
                    {tx.client_name && (
                      <div>
                        <span className="block text-xs text-slate-400">Client</span>
                        <span className="font-bold text-slate-900 dark:text-white">{tx.client_name}</span>
                      </div>
                    )}
                    <div>
                      <span className="block text-xs text-slate-400">Project</span>
                      <span className="font-medium text-slate-700 dark:text-slate-300">{tx.project}</span>
                    </div>
                  </div>
                  <div className="space-y-4 text-right">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest border-b border-slate-100 dark:border-slate-800 pb-2 mb-4">Information</h4>
                    <div>
                      <span className="block text-xs text-slate-400">ID</span>
                      <span className="font-mono text-slate-900 dark:text-white">#{tx.id}</span>
                    </div>
                    <div>
                      <span className="block text-xs text-slate-400">Date</span>
                      <span className="font-medium text-slate-700 dark:text-slate-300">{tx.date}</span>
                    </div>
                    {tx.due_date && (
                      <div>
                        <span className="block text-xs text-slate-400">Due Date</span>
                        <span className="font-medium text-slate-700 dark:text-slate-300">{tx.due_date}</span>
                      </div>
                    )}
                  </div>
                </div>

                <table className="w-full mb-12">
                  <thead>
                    <tr className="border-b-2 border-slate-100 dark:border-slate-800 text-left">
                      <th className="py-4 text-xs font-bold text-slate-400 uppercase tracking-widest pl-4">Description</th>
                      <th className="py-4 text-xs font-bold text-slate-400 uppercase tracking-widest text-right pr-4">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="py-6 pl-4">
                        <div className="font-bold text-slate-900 dark:text-white mb-1">{tx.desc}</div>
                        <div className="text-sm text-slate-500">{tx.project} • {tx.type}</div>
                      </td>
                      <td className="py-6 pr-4 text-right font-bold text-slate-900 dark:text-white">
                        {currency} {Math.abs(tx.amount).toLocaleString()}
                      </td>
                    </tr>
                  </tbody>
                  <tfoot>
                    <tr className="border-t-2 border-slate-900 dark:border-white">
                      <td className="py-6 pl-4 font-black text-xl text-slate-900 dark:text-white uppercase">Total</td>
                      <td className="py-6 pr-4 text-right font-black text-xl text-blue-600 dark:text-blue-400">
                        {currency} {Math.abs(tx.amount).toLocaleString()}
                      </td>
                    </tr>
                  </tfoot>
                </table>

                <div className="text-center pt-12 border-t border-slate-100 dark:border-slate-800">
                  <p className="text-xs text-slate-300 dark:text-slate-600 font-bold uppercase tracking-widest">
                    Generated by FinERP Financial Systems
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>

      <style>{`
        @media print {
          body * { visibility: hidden; }
          .fixed, .fixed * { visibility: visible; }
          .fixed { position: absolute; left: 0; top: 0; width: 100%; height: 100%; background: white; }
        }
      `}</style>
    </div>
  );
}
